---

- name: Create a Minecraft CR that does not agree to the EULA
  k8s:
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ name }}'
    namespace: '{{ namespace }}'
    wait: yes
    wait_timeout: 60
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  register: teula_cr_result

- name: Assert that an address has been set on the custom resource
  assert:
    that: teula_cr_result.result.status.address is defined

- name: Ping the server for 30 seconds
  command: 'mcstatus {{ teula_cr_result.result.status.address }} ping'
  changed_when: false
  retries: 10
  delay: 3
  register: mcstatus_status_raw
  until: not (mcstatus_status_raw is failed)
  ignore_errors: yes

- name: Assert the server was not reachable
  assert:
    that:
    - mcstatus_status_raw is failed

- name: Delete the Minecraft instance
  k8s:
    state: absent
    api_version: '{{ api_version }}'
    kind: '{{ kind }}'
    name: '{{ name }}'
    namespace: '{{ namespace }}'
    wait: yes
