---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    server:
      enable_query: yes
      motd: '{{ motd }}'
  roles:
    - minecraft-kubernetes
