---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: minecraft-server
    groups:
    - server
    box: centos/7
    memory: 4096
    cpus: 2
  - name: minecraft-client
    groups:
    - client
    box: centos/7
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      server:
        motd: "Minecraft deployed in Vagrant by Molecule"
  playbooks:
    converge: ../default/playbook.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
  lint:
    name: ansible-lint
